names:
  sword: "&6Dragon Sword"
  axe: "&5Dragon Axe"
  pickaxe: "&5Dragon Pickaxe"
  shovel: "&5Dragon Shovel"
  hoe: "&5Dragon Hoe"

  helmet: "&5Dragon Helmet"
  chestplate: "&5Dragon Chestplate"
  leggings: "&5Dragon Leggings"
  boots: "&5Dragon Boots"

  wings: "&5Dragon Wings"

required_material: DIAMOND

setbonus:
  enabled: true
  resistance_level: 1

# Durabillity Abnutzung
  durability:
    armor:
      reduction: 0.25   # 25 % weniger Haltbarkeitsschaden
    tools:
      reduction: 0.5   # 50 % weniger Haltbarkeitsschaden

# Damange und Abbau geschwindigkeit

combat:
  sword:
    bonus_damage: 10.0
    attack_speed: 2.0
  axe:
    bonus_damage: 15.0
    attack_speed: 0.8
  pickaxe:
    bonus_damage: 8.0
    attack_speed: 2.0
  shovel:
    bonus_damage: 8.0
    attack_speed: 1.5
  hoe:
    bonus_damage: 2.0
    attack_speed: 5.0

